//! conduit daemon — Windows side.
//!
//! M0 scope: advertise over mDNS, accept one LAN peer, Noise XX, keep the socket
//! honest, sync text clipboard both ways. The shape here is chosen so image sync adds
//! neither a thread nor a timer per message.

#![windows_subsystem = "windows"]

mod advert;
mod autostart;
mod clip;
mod config;
mod control;
mod data_dir;
mod explorer;
mod file;
mod image;
mod notification_history;
mod shared_links;
mod status;
mod toast;
mod tray;
mod verification_code;
mod wire;

use anyhow::{bail, Context, Result};
use prost::Message as _;
use std::io::Write as _;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::{broadcast, mpsc, Mutex};
use tracing::{info, warn};
use wire::{pb, Session};

const PORT: u16 = 41112;
/// Production Relay fleet. Windows parks one responder at each node; Android still keeps exactly
/// one active Relay/session and switches only on natural reconnect/failure events.
const DEFAULT_RELAYS: &str = "conduit-us.414222.xyz:41113;conduit-wa.414222.xyz:41113;conduit-tyo.414222.xyz:41113;conduit-jp.414222.xyz:41113";
/// ponytail: flat retry, no escalation. The desktop is on mains power and the relay is
/// ours, so there is nothing to be polite to; add backoff if it ever rate-limits.
const RELAY_RETRY: Duration = Duration::from_secs(15);
/// Silence this long and we make the peer prove the path is alive. KDE Connect's
/// bug 476747 is the counter-example: OS defaults meant ~7875 s to notice a dead peer.
const IDLE_PING: Duration = Duration::from_secs(60);
/// Over the relay the peer is on cellular or a foreign network, where every ping is a
/// radio wake on a battery. Four an hour instead of sixty, at the cost of noticing a
/// silently dead tunnel later. The phone's read deadline is 2.5x this and follows it.
const RELAY_IDLE_PING: Duration = Duration::from_secs(240);
const PONG_DEADLINE: Duration = Duration::from_secs(10);

/// State for one outstanding liveness challenge.
///
/// An ordinary inbound frame is proof that *one* direction still works, but it is not proof that
/// the peer received our PING. In particular, a half-dead VPN path can keep delivering phone -> PC
/// notification traffic while dropping PC -> phone bytes. Only the PONG generated by our PING may
/// clear this deadline. No timer is added here: the existing blocked receive is simply given the
/// earlier of the normal idle deadline and an already-outstanding PONG deadline.
struct Heartbeat {
    idle: Duration,
    pong_timeout: Duration,
    waiting_until: Option<tokio::time::Instant>,
}

impl Heartbeat {
    fn new(idle: Duration, pong_timeout: Duration) -> Self {
        Self {
            idle,
            pong_timeout,
            waiting_until: None,
        }
    }

    fn deadline(&self, quiet_for: Duration, now: tokio::time::Instant) -> tokio::time::Instant {
        self.waiting_until
            .unwrap_or_else(|| now + self.idle.saturating_sub(quiet_for))
    }

    fn awaiting_pong(&self) -> bool {
        self.waiting_until.is_some()
    }

    fn ping_sent(&mut self, now: tokio::time::Instant) {
        self.waiting_until = Some(now + self.pong_timeout);
    }

    /// Returns true only when this frame satisfies an outstanding liveness challenge.
    fn observe(&mut self, kind: pb::Kind) -> bool {
        if kind == pb::Kind::Pong && self.waiting_until.take().is_some() {
            true
        } else {
            false
        }
    }
}

#[derive(Default)]
struct Metrics {
    created: AtomicU64,
    closed: AtomicU64,
    frames_in: AtomicU64,
    frames_out: AtomicU64,
}

/// Increments `closed` on drop — normal return, error, panic or task abort alike —
/// so `created == closed` after quiesce holds without bookkeeping at every exit.
/// That invariant is the entire reason this project exists.
struct SessionGuard {
    metrics: Arc<Metrics>,
    status: Arc<status::StatusFile>,
}

struct RelayArrival {
    stream: TcpStream,
    endpoint: String,
}

struct PendingOutbound {
    transfer_id: Vec<u8>,
    name: String,
    completion: tokio::sync::oneshot::Sender<std::result::Result<(), String>>,
}

impl Drop for SessionGuard {
    fn drop(&mut self) {
        self.status.disconnected();
        let closed = self.metrics.closed.fetch_add(1, Ordering::Relaxed) + 1;
        info!(
            created = self.metrics.created.load(Ordering::Relaxed),
            closed,
            frames_in = self.metrics.frames_in.load(Ordering::Relaxed),
            frames_out = self.metrics.frames_out.load(Ordering::Relaxed),
            "session closed"
        );
    }
}

#[tokio::main(flavor = "multi_thread", worker_threads = 2)]
async fn main() -> Result<()> {
    // Keep the headless daemon, control surface, Start-menu shortcut and toast identity under one
    // Windows application identity. This must happen before any shell/toast interaction.
    unsafe {
        let _ = windows::Win32::UI::Shell::SetCurrentProcessExplicitAppUserModelID(
            &windows::core::HSTRING::from("Conduit.Desktop"),
        );
    }
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "conduit_daemon=info".into()),
        )
        .init();

    let mut args = std::env::args_os();
    let _exe = args.next();
    if let Some(command) = args.next() {
        if command == "send" {
            let path = args.next().context("usage: conduit-daemon send <file>")?;
            if args.next().is_some() {
                bail!("usage: conduit-daemon send <file>");
            }
            let mut stdout = std::io::stdout();
            let path = control::queue_with_progress(&PathBuf::from(path), |transferred, total| {
                let _ = writeln!(stdout, "PROGRESS {transferred} {total}");
            })
            .await?;
            // A GUI-subsystem command launched from Explorer may have no stdout handle. Output is
            // best-effort only; publication success belongs to the resident daemon/phone handshake.
            let _ = writeln!(stdout, "Sent to phone: {}", path.display());
            return Ok(());
        }
        if command == "autostart" {
            let action = args
                .next()
                .context("usage: conduit-daemon autostart <install|remove|status>")?;
            if args.next().is_some() {
                bail!("usage: conduit-daemon autostart <install|remove|status>");
            }
            match action.to_string_lossy().as_ref() {
                "install" => println!("Autostart installed: {}", autostart::install()?),
                "remove" => println!(
                    "Autostart {}",
                    if autostart::remove()? {
                        "removed"
                    } else {
                        "was not installed"
                    }
                ),
                "status" => match autostart::status() {
                    Some(value) => println!("Autostart installed: {value}"),
                    None => println!("Autostart not installed"),
                },
                _ => bail!("usage: conduit-daemon autostart <install|remove|status>"),
            }
            return Ok(());
        }
        if command == "explorer" {
            let action = args
                .next()
                .context("usage: conduit-daemon explorer <install|remove|status>")?;
            if args.next().is_some() {
                bail!("usage: conduit-daemon explorer <install|remove|status>");
            }
            match action.to_string_lossy().as_ref() {
                "install" => println!("Explorer integration installed: {}", explorer::install()?),
                "remove" => println!(
                    "Explorer integration {}",
                    if explorer::remove()? {
                        "removed"
                    } else {
                        "was not installed"
                    }
                ),
                "status" => match explorer::status() {
                    Some(value) => println!("Explorer integration installed: {value}"),
                    None => println!("Explorer integration not installed"),
                },
                _ => bail!("usage: conduit-daemon explorer <install|remove|status>"),
            }
            return Ok(());
        }
        if command == "reload" && args.next().is_none() {
            control::reload().await?;
            return Ok(());
        }
        if command == "config" {
            let dir = config_dir()?;
            std::fs::create_dir_all(&dir)?;
            let mut config = config::Config::load(&dir)?;
            let action = args.next().context(
                "usage: conduit-daemon config <show|relay-proxy <value|off>|relays <list|off>>",
            )?;
            match action.to_string_lossy().as_ref() {
                "show" if args.next().is_none() => {
                    println!("Config file: {}", dir.join("config.txt").display());
                    println!(
                        "relay_proxy={}",
                        config
                            .relay_proxy
                            .as_deref()
                            .filter(|v| !v.is_empty())
                            .unwrap_or("off")
                    );
                    println!(
                        "relays={}",
                        config.relays.as_deref().unwrap_or(DEFAULT_RELAYS)
                    );
                    if std::env::var_os("CONDUIT_RELAY_PROXY").is_some()
                        || std::env::var_os("CONDUIT_RELAYS").is_some()
                        || std::env::var_os("CONDUIT_RELAY").is_some()
                    {
                        println!(
                            "Note: one or more CONDUIT_* environment variables override this file."
                        );
                    }
                }
                "relay-proxy" => {
                    let value = args
                        .next()
                        .context("usage: conduit-daemon config relay-proxy <value|off>")?;
                    if args.next().is_some() {
                        bail!("usage: conduit-daemon config relay-proxy <value|off>");
                    }
                    let value = value.to_string_lossy();
                    config.relay_proxy = Some(if value.eq_ignore_ascii_case("off") {
                        String::new()
                    } else {
                        value.into_owned()
                    });
                    println!("Saved {}", config.save(&dir)?.display());
                    match control::reload().await {
                        Ok(()) => println!("Applied to the running daemon."),
                        Err(_) => println!("Saved; it will apply when the daemon next starts."),
                    }
                }
                "relays" => {
                    let value = args
                        .next()
                        .context("usage: conduit-daemon config relays <list|off>")?;
                    if args.next().is_some() {
                        bail!("usage: conduit-daemon config relays <list|off>");
                    }
                    let value = value.to_string_lossy();
                    config.relays = Some(if value.eq_ignore_ascii_case("off") {
                        String::new()
                    } else {
                        value.into_owned()
                    });
                    println!("Saved {}", config.save(&dir)?.display());
                    match control::reload().await {
                        Ok(()) => println!("Applied to the running daemon."),
                        Err(_) => println!("Saved; it will apply when the daemon next starts."),
                    }
                }
                _ => bail!(
                    "usage: conduit-daemon config <show|relay-proxy <value|off>|relays <list|off>>"
                ),
            }
            return Ok(());
        }
        if command == "status" && args.next().is_none() {
            let dir = config_dir()?;
            // The daemon itself owns 0.0.0.0:41112. Binding that exact address/port is a
            // side-effect-free, on-demand liveness check; binding only loopback can succeed on
            // Windows even while the wildcard listener exists and would therefore misreport.
            let daemon_running = std::net::TcpListener::bind(("0.0.0.0", PORT)).is_err();
            println!(
                "daemon={}",
                if daemon_running { "running" } else { "stopped" }
            );
            if let Some(snapshot) = status::read(&dir) {
                print!("{snapshot}");
            }
            return Ok(());
        }
        bail!(
            "unknown command {:?}; usage: conduit-daemon [send <file> | status | autostart <install|remove|status> | explorer <install|remove|status> | config ...]",
            command
        );
    }

    let dir = config_dir()?;
    std::fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    let user_config = config::Config::load(&dir)?;
    let desktop_status = Arc::new(status::StatusFile::new(&dir)?);
    let identity = wire::load_or_create_identity(&dir.join("identity.bin"))?;
    let device_id = wire::device_id(&identity.public);
    let fingerprint = wire::fingerprint(&identity.public);
    info!(id = %device_id, %fingerprint, "identity");

    // Bind before creating clipboard/toast/control workers. Besides being the LAN listener, this
    // is the process's zero-extra-resource single-instance gate: a manual launch racing the Run
    // entry exits here before it can own any long-lived Conduit resource.
    let listener = TcpListener::bind(("0.0.0.0", PORT))
        .await
        .with_context(|| {
            format!("binding Conduit listener on port {PORT}; is another daemon running?")
        })?;
    info!(port = PORT, "listening");

    // Optional tray icon. It is one blocked Win32 message loop and is not created at all when the
    // setting is off. Failures are non-fatal: transport and clipboard sync remain useful without it.
    let (tray_exit_tx, mut tray_exit_rx) = mpsc::unbounded_channel::<()>();
    let mut tray = if user_config.show_tray_icon() {
        match tray::Tray::start(&dir, tray_exit_tx.clone()) {
            Ok(tray) => {
                info!("tray icon up");
                Some(tray)
            }
            Err(e) => {
                warn!(error = %e, "tray icon unavailable");
                None
            }
        }
    } else {
        info!("tray icon disabled by config");
        None
    };

    let metrics = Arc::new(Metrics::default());
    // One listener thread for the process, started before the socket so a clip copied
    // during the first handshake is already in the ring.
    let bridge = Arc::new(clip::Bridge::start()?);
    // One ephemeral action bus from the already-resident toast thread back into the currently
    // active Noise session. It has no backlog semantics: with no live session receiver, a toast
    // click is dropped rather than replayed against a future/stale Android notification.
    let (toast_action_tx, _) = broadcast::channel::<pb::NotifAction>(16);
    // Likewise one toast thread. A failure here is not fatal: clipboard sync is still
    // worth having on a machine where the notification platform will not cooperate.
    let toasts = match toast::Notifier::start(&dir, toast_action_tx.clone(), bridge.clone()) {
        Ok(notifier) => Some(Arc::new(notifier)),
        Err(e) => {
            warn!(error = %e, "toasts unavailable, mirroring notifications is disabled");
            None
        }
    };
    // One local command queue for the process. File bytes never pass through this IPC; callers
    // name a local path and the resident daemon opens/streams it through its one live session.
    let (outbound_tx, outbound_rx) = mpsc::channel::<control::SendRequest>(16);
    let outbound = Arc::new(Mutex::new(outbound_rx));
    let (reload_tx, mut reload_rx) = mpsc::channel::<control::ReloadRequest>(4);
    tokio::spawn(async move {
        if let Err(e) = control::serve(outbound_tx, reload_tx).await {
            warn!(error = %e, "local control pipe stopped");
        }
    });
    // Bound, not dropped: this is what the phone's discovery burst finds. Advertised
    // only once the socket is accepting, so a resolve is never answered by a refusal.
    let _advert = advert::Advert::start(PORT, &device_id, &fingerprint)?;

    // M0 carries exactly one peer. A reconnect must win, so the previous session is
    // dropped rather than the new one refused: a half-open socket would otherwise
    // lock the phone out until its own keepalive gave up.
    //
    // Two ways in now, and the difference ends here: a relay stream is spliced to the
    // phone by a process that cannot read it, so from `serve`'s point of view it is an
    // ordinary socket carrying an ordinary Noise session.
    let mut relay_endpoints = user_config.resolved_relays(DEFAULT_RELAYS);
    let mut relay_proxy = user_config.resolved_proxy();
    info!(
        relays = ?relay_endpoints,
        proxy = relay_proxy.as_deref().unwrap_or("direct"),
        "relay configuration"
    );
    let (mut relay_tasks, mut relay_rx) =
        start_relay_workers(&relay_endpoints, &device_id, relay_proxy.clone());

    let mut active: Option<tokio::task::JoinHandle<()>> = None;
    let mut active_path: Option<&'static str> = None;
    loop {
        let (stream, peer, via, relay_endpoint) = tokio::select! {
            Some(()) = tray_exit_rx.recv() => {
                info!("exit requested from tray");
                break;
            }
            Some(request) = reload_rx.recv() => {
                let result = match config::Config::load(&dir) {
                    Err(e) => Err(format!("{e:#}")),
                    Ok(new_config) => {
                        let wanted_tray = new_config.show_tray_icon();
                        let new_relays = new_config.resolved_relays(DEFAULT_RELAYS);
                        let new_proxy = new_config.resolved_proxy();
                        let relay_changed = new_relays != relay_endpoints || new_proxy != relay_proxy;
                        let mut apply_error = None;

                        if wanted_tray != tray.is_some() {
                            if wanted_tray {
                                match tray::Tray::start(&dir, tray_exit_tx.clone()) {
                                    Ok(new_tray) => {
                                        tray = Some(new_tray);
                                        info!("tray icon enabled without daemon restart");
                                    }
                                    Err(e) => apply_error = Some(format!("starting tray icon: {e:#}")),
                                }
                            } else {
                                tray = None;
                                info!("tray icon disabled without daemon restart");
                            }
                        }

                        if relay_changed {
                            for task in relay_tasks.drain(..) {
                                task.abort();
                                let _ = task.await;
                            }
                            let (tasks, rx) =
                                start_relay_workers(&new_relays, &device_id, new_proxy.clone());
                            relay_tasks = tasks;
                            relay_rx = rx;
                            relay_endpoints = new_relays;
                            relay_proxy = new_proxy;
                            info!(
                                relays = ?relay_endpoints,
                                proxy = relay_proxy.as_deref().unwrap_or("direct"),
                                "relay configuration applied without daemon restart"
                            );
                            // A live relay socket belongs to the old routing configuration. End only
                            // that session so the phone reconnects through the newly parked routes;
                            // a LAN session is left untouched.
                            if active_path == Some("relay") {
                                if let Some(previous) = active.take() {
                                    previous.abort();
                                    let _ = previous.await;
                                }
                                active_path = None;
                            }
                        }

                        match apply_error {
                            Some(message) => Err(message),
                            None => Ok(()),
                        }
                    }
                };
                let _ = request.completion.send(result);
                continue;
            }
            accepted = listener.accept() => {
                let (stream, peer) = accepted?;
                (stream, peer, "lan", None)
            }
            Some(arrival) = relay_rx.recv() => {
                let peer = arrival.stream.peer_addr()?;
                (arrival.stream, peer, "relay", Some(arrival.endpoint))
            }
        };
        info!(%peer, via, relay = relay_endpoint.as_deref().unwrap_or("-"), "peer arriving");
        if let Some(previous) = active.take() {
            previous.abort();
            let _ = previous.await; // guard drop runs here — closed is counted
        }
        let created = metrics.created.fetch_add(1, Ordering::Relaxed) + 1;
        info!(
            created,
            closed = metrics.closed.load(Ordering::Relaxed),
            "session created"
        );
        let metrics = metrics.clone();
        let local_priv = identity.private.clone();
        let bridge = bridge.clone();
        let toasts = toasts.clone();
        let outbound = outbound.clone();
        let relay_endpoint = relay_endpoint.clone();
        let desktop_status = desktop_status.clone();
        let toast_action_tx = toast_action_tx.clone();
        let data_dir = dir.clone();
        active_path = Some(via);
        active = Some(tokio::spawn(async move {
            let _guard = SessionGuard {
                metrics: metrics.clone(),
                status: desktop_status.clone(),
            };
            if let Err(e) = serve(
                stream,
                peer,
                &local_priv,
                &metrics,
                &bridge,
                &outbound,
                toasts.as_deref(),
                via,
                relay_endpoint.as_deref(),
                &desktop_status,
                &toast_action_tx,
                &data_dir,
            )
            .await
            {
                warn!(%peer, error = %e, "session ended");
            }
        }));
    }

    if let Some(session) = active.take() {
        session.abort();
        let _ = session.await;
    }
    desktop_status.disconnected();
    Ok(())
}

fn start_relay_workers(
    relays: &[String],
    rendezvous: &str,
    relay_proxy: Option<String>,
) -> (
    Vec<tokio::task::JoinHandle<()>>,
    tokio::sync::mpsc::Receiver<RelayArrival>,
) {
    let (relay_tx, relay_rx) =
        tokio::sync::mpsc::channel::<RelayArrival>((relays.len().max(1) * 2).max(2));
    let mut tasks = Vec::with_capacity(relays.len());
    for endpoint in relays {
        info!(%endpoint, "parking at relay");
        tasks.push(tokio::spawn(park_forever(
            endpoint.clone(),
            rendezvous.to_owned(),
            relay_tx.clone(),
            relay_proxy.clone(),
        )));
    }
    // Only workers own senders. With no configured relays this closes the receiver and makes the
    // `Some(arrival)` select branch dormant without any poll or special timer.
    drop(relay_tx);
    (tasks, relay_rx)
}

/// Keeps exactly one connection parked at the relay for the life of the process.
///
/// Re-parks immediately after handing a stream over, so a reconnecting phone always
/// finds a partner already waiting instead of racing the desktop to the rendezvous.
/// The relay pairs whoever presents the id, so a stale park is harmless: the next
/// arrival is spliced to the newest one.
async fn park_forever(
    endpoint: String,
    rendezvous: String,
    tx: tokio::sync::mpsc::Sender<RelayArrival>,
    relay_proxy: Option<String>,
) {
    loop {
        match wire::park(&endpoint, &rendezvous, relay_proxy.as_deref()).await {
            Ok(stream) => {
                if let Err(e) = set_keepalive(&stream) {
                    warn!(error = %e, "relay stream without keepalive");
                }
                // Closed channel means main returned; nothing left to serve.
                if tx
                    .send(RelayArrival {
                        stream,
                        endpoint: endpoint.clone(),
                    })
                    .await
                    .is_err()
                {
                    return;
                }
            }
            Err(e) => {
                warn!(%endpoint, error = %e, "relay unreachable");
                tokio::time::sleep(RELAY_RETRY).await;
            }
        }
    }
}

async fn serve(
    mut stream: TcpStream,
    peer: SocketAddr,
    local_priv: &[u8],
    metrics: &Metrics,
    bridge: &Arc<clip::Bridge>,
    outbound: &Arc<Mutex<mpsc::Receiver<control::SendRequest>>>,
    toasts: Option<&toast::Notifier>,
    // "lan" or "relay". Only the keepalive interval and the log line care.
    path: &'static str,
    relay_endpoint: Option<&str>,
    desktop_status: &status::StatusFile,
    toast_action_tx: &broadcast::Sender<pb::NotifAction>,
    data_dir: &std::path::Path,
) -> Result<()> {
    stream.set_nodelay(true)?;
    set_keepalive(&stream)?;
    let idle_ping = if path == "relay" {
        RELAY_IDLE_PING
    } else {
        IDLE_PING
    };

    let mut session = Session::handshake(&mut stream, local_priv, false).await?;
    info!(
        %peer,
        id = %wire::device_id(&session.peer_static),
        via = path,
        relay = relay_endpoint.unwrap_or("-"),
        "session up"
    );
    desktop_status.linked(&wire::device_id(&session.peer_static), path, relay_endpoint);
    // The phone has no other way to learn this machine's name. mDNS carries it, but a
    // relay session never sees an mDNS record — and off-LAN is precisely when a phone
    // showing "the desktop" instead of a name is least useful. Sent unprompted and
    // unanswered: the handshake already settled who the peer is.
    let hello = pb::PairRequest {
        device_id: wire::device_id(&session.peer_static),
        device_name: advert::hostname(),
        static_pub: Vec::new(),
        version: env!("CARGO_PKG_VERSION").to_string(),
    };
    session
        .send(&mut stream, pb::Kind::PairRequest, &hello.encode_to_vec())
        .await?;
    metrics.frames_out.fetch_add(1, Ordering::Relaxed);
    // Subscribed after the handshake so the session does not replay clips copied
    // while it was still connecting.
    let mut clips = bridge.subscribe();
    // Same semantics for user-initiated toast actions: only the live authenticated session may
    // consume them, and broadcast deliberately has no durable queue across reconnects.
    let mut toast_actions = toast_action_tx.subscribe();
    // At most one image in flight, and it dies with the session: a peer that vanishes
    // mid-transfer cannot leave a partial buffer behind for the next one to inherit.
    let mut incoming: Option<image::Assembly> = None;
    // Same rule for a file, with teeth: `Incoming`'s Drop deletes the partial, so a
    // session ending mid-transfer cannot leave scratch files in Downloads.
    let mut arriving: Option<file::Incoming> = None;
    // One desktop->phone file may be awaiting its receiver-side publication result. Other local
    // requests stay in the bounded control queue until this completes, so results cannot cross.
    let mut pending_outbound: Option<PendingOutbound> = None;
    let mut heartbeat = Heartbeat::new(idle_ping, PONG_DEADLINE);

    loop {
        // Time left before this side owes the peer a frame. Measured from our last
        // *send*, not from the last thing we heard: the phone's read deadline can only
        // be satisfied by us speaking, so a phone that chats steadily while hearing
        // nothing back used to tear down a perfectly healthy session on the dot. It
        // also still catches a dead peer, because a ping demands a pong.
        let deadline = heartbeat.deadline(session.quiet_for(), tokio::time::Instant::now());
        // `recv` is cancel-safe, which is what makes racing it legal. `send` is not,
        // but a `select!` branch body runs to completion once chosen, so the sends
        // below are never cancelled mid-frame. While a PONG is outstanding, local outbound
        // work pauses for at most ten seconds so it cannot hide the liveness deadline.
        let envelope = tokio::select! {
            result = tokio::time::timeout_at(deadline, session.recv(&mut stream)) => match result {
                Ok(envelope) => envelope?,
                Err(_) if heartbeat.awaiting_pong() => {
                    bail!("peer silent past pong deadline")
                }
                Err(_) => {
                    session.send(&mut stream, pb::Kind::Ping, &[]).await?;
                    metrics.frames_out.fetch_add(1, Ordering::Relaxed);
                    heartbeat.ping_sent(tokio::time::Instant::now());
                    continue;
                }
            },
            local = clips.recv(), if !heartbeat.awaiting_pong() => {
                match local {
                    Ok(clip::Clip::Text(text)) => {
                        let clip = pb::ClipText {
                            timestamp_ms: now_ms(),
                            mime: "text/plain".into(),
                            text,
                        };
                        session
                            .send(&mut stream, pb::Kind::ClipText, &clip.encode_to_vec())
                            .await?;
                        metrics.frames_out.fetch_add(1, Ordering::Relaxed);
                    }
                    Ok(clip::Clip::Image(png)) => {
                        info!(bytes = png.len(), "clip image out");
                        let frames = image::send(&mut session, &mut stream, &png, false, false).await?;
                        metrics.frames_out.fetch_add(frames, Ordering::Relaxed);
                    }
                    // The ring overwrote clips faster than this session drained them.
                    // Skipping is correct: only the newest clipboard state matters.
                    Err(broadcast::error::RecvError::Lagged(n)) => {
                        warn!(skipped = n, "clip ring lagged")
                    }
                    Err(broadcast::error::RecvError::Closed) => {
                        anyhow::bail!("clipboard bridge is gone")
                    }
                }
                continue;
            }
            local_file = async {
                let mut rx = outbound.lock().await;
                rx.recv().await
            }, if pending_outbound.is_none() && !heartbeat.awaiting_pong() => {
                let Some(request) = local_file else {
                    bail!("local outbound file queue closed")
                };
                let control::SendRequest { path, completion, progress } = request;
                // Refuse a bad/missing local path before FILE_OFFER reaches the phone. Once an
                // offer is on the wire, a read/send error ends this session so Android drops its
                // pending MediaStore row rather than inheriting a partial into the next session.
                match file::Outbound::open(&path).await {
                    Ok(outbound_file) => {
                        let name = outbound_file.name().to_string();
                        let transfer_id = outbound_file.transfer_id().to_vec();
                        match outbound_file
                            .send(&mut session, &mut stream, |transferred, total| {
                                let _ = progress.send(control::TransferProgress { transferred, total });
                            })
                            .await
                        {
                            Ok(frames) => {
                                metrics.frames_out.fetch_add(frames, Ordering::Relaxed);
                                pending_outbound = Some(PendingOutbound {
                                    transfer_id,
                                    name,
                                    completion,
                                });
                            }
                            Err(e) => {
                                let message = format!("sending {name} to the phone: {e:#}");
                                let _ = completion.send(Err(message.clone()));
                                return Err(e).with_context(|| format!("sending {name} to the phone"));
                            }
                        }
                    }
                    Err(e) => {
                        let message = format!("opening {}: {e:#}", path.display());
                        let _ = completion.send(Err(message));
                        warn!(path = %path.display(), error = %e, "local file was not sent");
                    }
                }
                continue;
            }
            action = toast_actions.recv(), if !heartbeat.awaiting_pong() => {
                match action {
                    Ok(action) => {
                        session
                            .send(&mut stream, pb::Kind::NotifAction, &action.encode_to_vec())
                            .await?;
                        metrics.frames_out.fetch_add(1, Ordering::Relaxed);
                    }
                    Err(broadcast::error::RecvError::Lagged(n)) => {
                        // User clicks are rare. If something ever floods this bounded channel,
                        // dropping old actions is safer than executing stale capabilities later.
                        warn!(skipped = n, "toast action ring lagged");
                    }
                    Err(broadcast::error::RecvError::Closed) => {
                        warn!("toast action channel closed");
                    }
                }
                continue;
            }
        };
        metrics.frames_in.fetch_add(1, Ordering::Relaxed);
        heartbeat.observe(envelope.kind());

        match envelope.kind() {
            pb::Kind::Ping => {
                session.send(&mut stream, pb::Kind::Pong, &[]).await?;
                metrics.frames_out.fetch_add(1, Ordering::Relaxed);
            }
            pb::Kind::Pong => {}
            pb::Kind::ClipText => {
                let clip = pb::ClipText::decode(&envelope.payload[..])?;
                info!(bytes = clip.text.len(), mime = %clip.mime, "clip text in");
                // A clipboard failure is the peer's problem, not the session's.
                if let Err(e) = bridge.apply(&clip.text) {
                    warn!(error = %e, "could not set the clipboard");
                }
            }
            // A bad image is dropped, never fatal — same rule as a bad notification.
            // The peer controls every field here, so a refused header must cost this
            // side an allocation of zero and the session nothing at all.
            pb::Kind::ClipImageHeader => {
                let header = pb::ClipImageHeader::decode(&envelope.payload[..])?;
                match image::Assembly::begin(&header) {
                    Ok(assembly) => {
                        info!(
                            bytes = header.total_bytes,
                            chunks = header.chunk_count,
                            mime = %header.mime,
                            photo = header.photo,
                            screenshot = header.screenshot,
                            "image in, receiving"
                        );
                        incoming = Some(assembly);
                    }
                    Err(e) => {
                        warn!(error = %e, "refused an image header");
                        incoming = None;
                    }
                }
            }
            pb::Kind::ClipImageChunk => {
                let chunk = pb::ClipImageChunk::decode(&envelope.payload[..])?;
                let Some(assembly) = incoming.as_mut() else {
                    warn!(index = chunk.index, "image chunk with no header, dropped");
                    continue;
                };
                match assembly.push(&chunk) {
                    Ok(None) => {}
                    Ok(Some(png)) => {
                        let photo = assembly.is_photo();
                        let screenshot = assembly.is_screenshot();
                        incoming = None;
                        info!(bytes = png.len(), photo, screenshot, "image complete");
                        if photo || screenshot {
                            // Never the clipboard. Camera photos and screenshots are capture
                            // events, not copy events. A screenshot also sets photo=true for
                            // backward safety, while the explicit bit selects the right toast.
                            match toasts {
                                Some(toasts) => {
                                    match tokio::task::spawn_blocking(move || stage_capture(&png))
                                        .await
                                    {
                                        Ok(Ok(path)) => {
                                            if screenshot {
                                                toasts.post(toast::Cmd::Screenshot { path });
                                            } else {
                                                toasts.post(toast::Cmd::Photo { path });
                                            }
                                        }
                                        Ok(Err(e)) => {
                                            warn!(error = %e, "could not stage the capture")
                                        }
                                        Err(e) => warn!(error = %e, "capture staging task failed"),
                                    }
                                }
                                None => info!("capture dropped, toasts are unavailable"),
                            }
                        } else {
                            // Decode, encode and two clipboard opens: too slow for a
                            // worker, and COM work regardless.
                            let bridge = bridge.clone();
                            match tokio::task::spawn_blocking(move || {
                                // Normalise first: the phone sends a camera JPEG as-is,
                                // and the PNG clipboard format must hold a real PNG.
                                let png = image::to_png(&png)?;
                                bridge.apply_image(&png)
                            })
                            .await
                            {
                                Ok(Err(e)) => {
                                    warn!(error = %e, "could not set the clipboard image")
                                }
                                Err(e) => warn!(error = %e, "clipboard image task failed"),
                                Ok(Ok(())) => {}
                            }
                        }
                    }
                    Err(e) => {
                        warn!(error = %e, "image transfer dropped");
                        incoming = None;
                    }
                }
            }
            pb::Kind::SharedUrl => {
                let shared = pb::SharedUrl::decode(&envelope.payload[..])?;
                let scheme = shared.url.to_ascii_lowercase();
                if !scheme.starts_with("http://") && !scheme.starts_with("https://") {
                    warn!(url = %shared.url, "refused non-web shared URL");
                    continue;
                }
                info!(url = %shared.url, source = %shared.source_device, "shared URL in");
                if let Err(e) = shared_links::record(
                    data_dir,
                    &shared.url,
                    &shared.title,
                    &shared.source_device,
                    shared.timestamp_ms,
                ) {
                    // History is convenience UI, never a reason to break the transport session.
                    warn!(error = %e, "could not record shared URL history");
                }
                if let Some(toasts) = toasts {
                    toasts.post(toast::Cmd::SharedUrl {
                        url: shared.url,
                        title: shared.title,
                        source: shared.source_device,
                    });
                }
            }
            // A malformed notification is dropped, never fatal: the phone's shade must
            // not be able to end a session that is also carrying the clipboard.
            pb::Kind::NotifNew => {
                let notif = pb::NotifNew::decode(&envelope.payload[..])?;
                info!(app = %notif.app_name, pkg = %notif.package, messages = notif.messages.len(), "notif in");
                let app = if notif.app_name.is_empty() {
                    notif.package.clone()
                } else {
                    notif.app_name.clone()
                };
                if let Err(e) = notification_history::record_new(
                    data_dir,
                    &notif.key,
                    &notif.package,
                    &app,
                    &notif.title,
                    &notif.text,
                    notif.timestamp_ms,
                ) {
                    warn!(error = %e, "could not record notification history");
                }
                if let Some(toasts) = toasts {
                    toasts.post(toast::Cmd::Show {
                        key: notif.key,
                        package: notif.package,
                        app,
                        title: notif.title,
                        body: notif.text,
                        messages: notif.messages,
                        app_icon: notif.app_icon_png,
                        avatar: notif.large_icon_png,
                        actions: notif.actions,
                        suppress_popup: notif.suppress_popup,
                    });
                }
            }
            pb::Kind::NotifUpdate => {
                let notif = pb::NotifUpdate::decode(&envelope.payload[..])?;
                if let Err(e) = notification_history::record_update(
                    data_dir,
                    &notif.key,
                    &notif.title,
                    &notif.text,
                ) {
                    warn!(error = %e, "could not update notification history");
                }
                if let Some(toasts) = toasts {
                    toasts.post(toast::Cmd::Update {
                        key: notif.key,
                        title: notif.title,
                        body: notif.text,
                        messages: notif.messages,
                    });
                }
            }
            pb::Kind::NotifRemove => {
                let notif = pb::NotifRemove::decode(&envelope.payload[..])?;
                if let Some(toasts) = toasts {
                    toasts.post(toast::Cmd::Hide { key: notif.key });
                }
            }
            // The phone announcing itself. Nothing to do with it on this side yet — the
            // desktop already knows which peer it is talking to — but decoding it keeps it
            // out of the "unhandled kind" log.
            pb::Kind::PairRequest => {
                let hello = pb::PairRequest::decode(&envelope.payload[..])?;
                info!(name = %hello.device_name, version = %hello.version, "peer named itself");
                desktop_status.peer_name(&hello.device_name);
            }
            // A file, same leniency as an image: a refused offer costs the transfer and
            // nothing else. The session is also carrying the clipboard, and a phone that
            // shares a 600 MB video must not knock it out.
            pb::Kind::FileOffer => {
                let offer = pb::FileOffer::decode(&envelope.payload[..])?;
                // Receive-folder changes are rare and file offers are rarer still. Reading the
                // tiny config here applies a newly selected folder to the next transfer without
                // a watcher, polling task, or forced reconnect.
                let configured_receive_dir = match config::Config::load(data_dir) {
                    Ok(config) => config.receive_dir,
                    Err(e) => {
                        warn!(error = %e, "could not read receive folder; falling back to Downloads");
                        None
                    }
                };
                let dir = match file::downloads(configured_receive_dir.as_deref()) {
                    Ok(dir) => dir,
                    Err(e) => {
                        warn!(error = %e, "no receive folder, file refused");
                        arriving = None;
                        continue;
                    }
                };
                match file::Incoming::begin(&offer, &dir) {
                    Ok(rx) => {
                        info!(
                            name = rx.name(),
                            bytes = offer.total_bytes,
                            chunks = offer.chunk_count,
                            mime = %offer.mime,
                            "file in, receiving"
                        );
                        arriving = Some(rx);
                    }
                    Err(e) => {
                        warn!(error = %e, "refused a file offer");
                        arriving = None;
                    }
                }
            }
            pb::Kind::FileChunk => {
                let chunk = pb::FileChunk::decode(&envelope.payload[..])?;
                let Some(rx) = arriving.as_mut() else {
                    warn!(index = chunk.index, "file chunk with no offer, dropped");
                    continue;
                };
                match rx.push(&chunk) {
                    Ok(None) => {}
                    Ok(Some(path)) => {
                        arriving = None;
                        match toasts {
                            Some(toasts) => toasts.post(toast::Cmd::File { path }),
                            None => info!("file arrived, but toasts are unavailable to say so"),
                        }
                    }
                    Err(e) => {
                        warn!(error = %e, "file transfer dropped");
                        // Assigning None runs the Drop that deletes the partial.
                        arriving = None;
                    }
                }
            }
            pb::Kind::FileResult => {
                let result = pb::FileResult::decode(&envelope.payload[..])?;
                let Some(pending) = pending_outbound.take() else {
                    warn!("file result arrived with no desktop transfer pending");
                    continue;
                };
                if result.transfer_id != pending.transfer_id {
                    warn!(
                        name = %pending.name,
                        "file result belongs to a different transfer, ignored"
                    );
                    pending_outbound = Some(pending);
                    continue;
                }
                if result.success {
                    info!(name = %pending.name, "phone published file");
                    let _ = pending.completion.send(Ok(()));
                } else {
                    let reason = if result.error.is_empty() {
                        "receiver refused the file".to_string()
                    } else {
                        result.error
                    };
                    warn!(name = %pending.name, error = %reason, "phone refused file");
                    let _ = pending.completion.send(Err(reason));
                }
            }
            other => warn!(?other, "unhandled kind"),
        }
    }
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Writes the newest phone capture where the shell and Snipping Tool can both read it.
///
/// One file, overwritten each time, which is the same bound as the single capture toast
/// that names it. No transcode: the toast image loader and Snipping Tool each read JPEG
/// happily, the phone already downscaled it, and re-encoding a photograph as PNG would
/// multiply its size for nothing — local toast images are capped at 3 MB.
fn stage_capture(bytes: &[u8]) -> Result<PathBuf> {
    let (name, stale) = if bytes.starts_with(b"\x89PNG") {
        ("capture.png", "capture.jpg")
    } else {
        ("capture.jpg", "capture.png")
    };
    let dir = config_dir()?;
    // Switching between a JPEG camera photo and a PNG screenshot must not leave a second
    // staged capture behind. Best effort: the old toast/token is replaced in the same slot.
    let _ = std::fs::remove_file(dir.join(stale));
    let path = dir.join(name);
    std::fs::write(&path, bytes).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// 30 s idle / 10 s probe / 3 retries. Windows' `SIO_KEEPALIVE_VALS` has no retry
/// count, so socket2 only exposes `with_retries` elsewhere.
fn set_keepalive(stream: &TcpStream) -> Result<()> {
    let keepalive = socket2::TcpKeepalive::new()
        .with_time(Duration::from_secs(30))
        .with_interval(Duration::from_secs(10));
    #[cfg(not(windows))]
    let keepalive = keepalive.with_retries(3);
    socket2::SockRef::from(stream).set_tcp_keepalive(&keepalive)?;
    Ok(())
}

fn config_dir() -> Result<PathBuf> {
    data_dir::resolve()
}

#[cfg(test)]
mod heartbeat_tests {
    use super::*;

    #[test]
    fn only_a_pong_satisfies_an_outstanding_liveness_challenge() {
        let now = tokio::time::Instant::now();
        let mut heartbeat = Heartbeat::new(Duration::from_secs(240), Duration::from_secs(10));

        assert_eq!(heartbeat.deadline(Duration::from_secs(240), now), now);
        heartbeat.ping_sent(now);
        assert!(heartbeat.awaiting_pong());
        assert_eq!(
            heartbeat.deadline(Duration::ZERO, now + Duration::from_secs(5)),
            now + Duration::from_secs(10),
            "ordinary traffic must not move the absolute PONG deadline",
        );

        assert!(!heartbeat.observe(pb::Kind::ClipText));
        assert!(
            heartbeat.awaiting_pong(),
            "an ordinary frame incorrectly counted as PONG"
        );
        assert!(heartbeat.observe(pb::Kind::Pong));
        assert!(!heartbeat.awaiting_pong());
    }
}
